name: Hello World

# トリガー設定: pushとpull_requestで実行
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  hello:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Say Hello
      run: echo "Hello, GitHub Actions!"
    
    - name: Show current date
      run: date
    
    - name: List files
      run: ls -la
